#!/usr/bin/python

import rgtp

a=rgtp.fancy("rgtp-serv.groggs.group.cam.ac.uk", 1431, 0)

#a.login("thomas@thurman.org.uk", "B0053B03D9340388")

a.raise_access_level(1)
print a.stat("R0381651")
#print a.index()
#print a.item("R0381651")
#print a.motd()
#print a.request_account("")
