#!/usr/bin/python

import rgtp

a=rgtp.fancy("rgtp-serv.groggs.group.cam.ac.uk", 1431, 0)
#a.login("thomas@thurman.org.uk", "B0053B03D9340388")
a.login("guest", 0)
print a.index()
#print a.item("R0381651")
#print a.motd()
#print a.request_account("")
a.logout()
